name: Screenshot Sender

on:
  schedule:
    - cron: "0 0 */3 * *"   # 每 3 天运行一次（UTC 00:00）
  workflow_dispatch:        # 仍然保留手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y xvfb google-chrome-stable python3 python3-pip

      - name: Install Python deps
        run: pip install DrissionPage xvfbwrapper requests

      - name: Run script
        run: xvfb-run -a python3 main.py
